//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.24 at 09:58:25 PM EDT 
//


package org.o2i2b2.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Com"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "com"
})
@XmlRootElement(name = "CommentsDeterminingExclusion")
public class CommentsDeterminingExclusion {

    @XmlElement(name = "Com", required = true)
    protected Com com;

    /**
     * Gets the value of the com property.
     * 
     * @return
     *     possible object is
     *     {@link Com }
     *     
     */
    public Com getCom() {
        return com;
    }

    /**
     * Sets the value of the com property.
     * 
     * @param value
     *     allowed object is
     *     {@link Com }
     *     
     */
    public void setCom(Com value) {
        this.com = value;
    }

}
