//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.24 at 09:58:25 PM EDT 
//


package org.o2i2b2.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Units"/>
 *         &lt;element ref="{}MultiplyingFactor"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "units",
    "multiplyingFactor"
})
@XmlRootElement(name = "ConvertingUnits")
public class ConvertingUnits {

    @XmlElement(name = "Units", required = true)
    protected Units units;
    @XmlElement(name = "MultiplyingFactor", required = true)
    protected MultiplyingFactor multiplyingFactor;

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link Units }
     *     
     */
    public Units getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link Units }
     *     
     */
    public void setUnits(Units value) {
        this.units = value;
    }

    /**
     * Gets the value of the multiplyingFactor property.
     * 
     * @return
     *     possible object is
     *     {@link MultiplyingFactor }
     *     
     */
    public MultiplyingFactor getMultiplyingFactor() {
        return multiplyingFactor;
    }

    /**
     * Sets the value of the multiplyingFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiplyingFactor }
     *     
     */
    public void setMultiplyingFactor(MultiplyingFactor value) {
        this.multiplyingFactor = value;
    }

}
