//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.24 at 09:58:25 PM EDT 
//


package org.o2i2b2.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NormalUnits" maxOccurs="unbounded"/>
 *         &lt;element ref="{}EqualUnits" maxOccurs="unbounded"/>
 *         &lt;element ref="{}ExcludingUnits"/>
 *         &lt;element ref="{}ConvertingUnits"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "normalUnits",
    "equalUnits",
    "excludingUnits",
    "convertingUnits"
})
@XmlRootElement(name = "UnitValues")
public class UnitValues {

    @XmlElement(name = "NormalUnits", required = true)
    protected List<String> normalUnits;
    @XmlElement(name = "EqualUnits", required = true)
    protected List<String> equalUnits;
    @XmlElement(name = "ExcludingUnits", required = true)
    protected ExcludingUnits excludingUnits;
    @XmlElement(name = "ConvertingUnits", required = true)
    protected ConvertingUnits convertingUnits;

    public void setNormalUnits(ArrayList<String> normalUnits) {
    	this.normalUnits = normalUnits;
    }
    
    public void addNormalUnit(String normalUnit) {
        if (normalUnits == null) {
            normalUnits = new ArrayList<String>();
        }
        normalUnits.add(normalUnit);
    }
    public void setEqualUnits(ArrayList<String> equalUnits) {
    	this.equalUnits = equalUnits;
    }
    
    public void addEqualUnit(String equalUnit) {
        if (equalUnits == null) {
        	equalUnits = new ArrayList<String>();
        }
        equalUnits.add(equalUnit);
    }
    /**
     * Gets the value of the normalUnits property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the normalUnits property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNormalUnits().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNormalUnits() {
        if (normalUnits == null) {
            normalUnits = new ArrayList<String>();
        }
        return this.normalUnits;
    }

    /**
     * Gets the value of the equalUnits property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equalUnits property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEqualUnits().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEqualUnits() {
        if (equalUnits == null) {
            equalUnits = new ArrayList<String>();
        }
        return this.equalUnits;
    }

    /**
     * Gets the value of the excludingUnits property.
     * 
     * @return
     *     possible object is
     *     {@link ExcludingUnits }
     *     
     */
    public ExcludingUnits getExcludingUnits() {
        return excludingUnits;
    }

    /**
     * Sets the value of the excludingUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExcludingUnits }
     *     
     */
    public void setExcludingUnits(ExcludingUnits value) {
        this.excludingUnits = value;
    }

    /**
     * Gets the value of the convertingUnits property.
     * 
     * @return
     *     possible object is
     *     {@link ConvertingUnits }
     *     
     */
    public ConvertingUnits getConvertingUnits() {
        return convertingUnits;
    }

    /**
     * Sets the value of the convertingUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConvertingUnits }
     *     
     */
    public void setConvertingUnits(ConvertingUnits value) {
        this.convertingUnits = value;
    }

}
