//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.06 at 12:45:02 PM EDT 
//


package org.o2i2b2.i2b2.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openmrs.module.o2i2b2.i2b2.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openmrs.module.o2i2b2.i2b2.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link O2I2B2 }
     * 
     */
    public O2I2B2 createO2I2B2() {
        return new O2I2B2();
    }

    /**
     * Create an instance of {@link Observation }
     * 
     */
    public Observation createObservation() {
        return new Observation();
    }

    /**
     * Create an instance of {@link Encounters }
     * 
     */
    public Encounters createEncounters() {
        return new Encounters();
    }

    /**
     * Create an instance of {@link Sources }
     * 
     */
    public Sources createSources() {
        return new Sources();
    }

    /**
     * Create an instance of {@link Patients }
     * 
     */
    public Patients createPatients() {
        return new Patients();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link Concept }
     * 
     */
    public Concept createConcept() {
        return new Concept();
    }

    /**
     * Create an instance of {@link Concepts }
     * 
     */
    public Concepts createConcepts() {
        return new Concepts();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link Ontology }
     * 
     */
    public Ontology createOntology() {
        return new Ontology();
    }

    /**
     * Create an instance of {@link Encounter }
     * 
     */
    public Encounter createEncounter() {
        return new Encounter();
    }

    /**
     * Create an instance of {@link Observations }
     * 
     */
    public Observations createObservations() {
        return new Observations();
    }

    /**
     * Create an instance of {@link Provider }
     * 
     */
    public Provider createProvider() {
        return new Provider();
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link Providers }
     * 
     */
    public Providers createProviders() {
        return new Providers();
    }

}
